/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kickthedrawer.ynab.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kickthedrawer.ynab.model.ScheduledTransactionDetail;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.kickthedrawer.ynab.JSON;

/**
 * ScheduledTransactionsResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-18T14:52:04.431395-07:00[America/Phoenix]")
public class ScheduledTransactionsResponseData {
  public static final String SERIALIZED_NAME_SCHEDULED_TRANSACTIONS = "scheduled_transactions";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_TRANSACTIONS)
  private List<ScheduledTransactionDetail> scheduledTransactions = new ArrayList<>();

  public static final String SERIALIZED_NAME_SERVER_KNOWLEDGE = "server_knowledge";
  @SerializedName(SERIALIZED_NAME_SERVER_KNOWLEDGE)
  private Long serverKnowledge;

  public ScheduledTransactionsResponseData() {
  }

  public ScheduledTransactionsResponseData scheduledTransactions(List<ScheduledTransactionDetail> scheduledTransactions) {
    
    this.scheduledTransactions = scheduledTransactions;
    return this;
  }

  public ScheduledTransactionsResponseData addScheduledTransactionsItem(ScheduledTransactionDetail scheduledTransactionsItem) {
    this.scheduledTransactions.add(scheduledTransactionsItem);
    return this;
  }

   /**
   * Get scheduledTransactions
   * @return scheduledTransactions
  **/
  @javax.annotation.Nonnull

  public List<ScheduledTransactionDetail> getScheduledTransactions() {
    return scheduledTransactions;
  }


  public void setScheduledTransactions(List<ScheduledTransactionDetail> scheduledTransactions) {
    this.scheduledTransactions = scheduledTransactions;
  }


  public ScheduledTransactionsResponseData serverKnowledge(Long serverKnowledge) {
    
    this.serverKnowledge = serverKnowledge;
    return this;
  }

   /**
   * The knowledge of the server
   * @return serverKnowledge
  **/
  @javax.annotation.Nonnull

  public Long getServerKnowledge() {
    return serverKnowledge;
  }


  public void setServerKnowledge(Long serverKnowledge) {
    this.serverKnowledge = serverKnowledge;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduledTransactionsResponseData scheduledTransactionsResponseData = (ScheduledTransactionsResponseData) o;
    return Objects.equals(this.scheduledTransactions, scheduledTransactionsResponseData.scheduledTransactions) &&
        Objects.equals(this.serverKnowledge, scheduledTransactionsResponseData.serverKnowledge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scheduledTransactions, serverKnowledge);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduledTransactionsResponseData {\n");
    sb.append("    scheduledTransactions: ").append(toIndentedString(scheduledTransactions)).append("\n");
    sb.append("    serverKnowledge: ").append(toIndentedString(serverKnowledge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("scheduled_transactions");
    openapiFields.add("server_knowledge");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("scheduled_transactions");
    openapiRequiredFields.add("server_knowledge");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ScheduledTransactionsResponseData
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ScheduledTransactionsResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ScheduledTransactionsResponseData is not found in the empty JSON string", ScheduledTransactionsResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ScheduledTransactionsResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ScheduledTransactionsResponseData` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ScheduledTransactionsResponseData.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("scheduled_transactions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `scheduled_transactions` to be an array in the JSON string but got `%s`", jsonObj.get("scheduled_transactions").toString()));
      }

      JsonArray jsonArrayscheduledTransactions = jsonObj.getAsJsonArray("scheduled_transactions");
      // validate the required field `scheduled_transactions` (array)
      for (int i = 0; i < jsonArrayscheduledTransactions.size(); i++) {
        ScheduledTransactionDetail.validateJsonObject(jsonArrayscheduledTransactions.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScheduledTransactionsResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScheduledTransactionsResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScheduledTransactionsResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScheduledTransactionsResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<ScheduledTransactionsResponseData>() {
           @Override
           public void write(JsonWriter out, ScheduledTransactionsResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScheduledTransactionsResponseData read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ScheduledTransactionsResponseData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ScheduledTransactionsResponseData
  * @throws IOException if the JSON string is invalid with respect to ScheduledTransactionsResponseData
  */
  public static ScheduledTransactionsResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScheduledTransactionsResponseData.class);
  }

 /**
  * Convert an instance of ScheduledTransactionsResponseData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

