/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kickthedrawer.ynab.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BulkResponseDataBulk
 */
public class BulkResponseDataBulkTest {
    private final BulkResponseDataBulk model = new BulkResponseDataBulk();

    /**
     * Model tests for BulkResponseDataBulk
     */
    @Test
    public void testBulkResponseDataBulk() {
        // TODO: test BulkResponseDataBulk
    }

    /**
     * Test the property 'transactionIds'
     */
    @Test
    public void transactionIdsTest() {
        // TODO: test transactionIds
    }

    /**
     * Test the property 'duplicateImportIds'
     */
    @Test
    public void duplicateImportIdsTest() {
        // TODO: test duplicateImportIds
    }

}
