/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kickthedrawer.ynab.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Category
 */
public class CategoryTest {
    private final Category model = new Category();

    /**
     * Model tests for Category
     */
    @Test
    public void testCategory() {
        // TODO: test Category
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'categoryGroupId'
     */
    @Test
    public void categoryGroupIdTest() {
        // TODO: test categoryGroupId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'hidden'
     */
    @Test
    public void hiddenTest() {
        // TODO: test hidden
    }

    /**
     * Test the property 'originalCategoryGroupId'
     */
    @Test
    public void originalCategoryGroupIdTest() {
        // TODO: test originalCategoryGroupId
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'budgeted'
     */
    @Test
    public void budgetedTest() {
        // TODO: test budgeted
    }

    /**
     * Test the property 'activity'
     */
    @Test
    public void activityTest() {
        // TODO: test activity
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'goalType'
     */
    @Test
    public void goalTypeTest() {
        // TODO: test goalType
    }

    /**
     * Test the property 'goalDay'
     */
    @Test
    public void goalDayTest() {
        // TODO: test goalDay
    }

    /**
     * Test the property 'goalCadence'
     */
    @Test
    public void goalCadenceTest() {
        // TODO: test goalCadence
    }

    /**
     * Test the property 'goalCadenceFrequency'
     */
    @Test
    public void goalCadenceFrequencyTest() {
        // TODO: test goalCadenceFrequency
    }

    /**
     * Test the property 'goalCreationMonth'
     */
    @Test
    public void goalCreationMonthTest() {
        // TODO: test goalCreationMonth
    }

    /**
     * Test the property 'goalTarget'
     */
    @Test
    public void goalTargetTest() {
        // TODO: test goalTarget
    }

    /**
     * Test the property 'goalTargetMonth'
     */
    @Test
    public void goalTargetMonthTest() {
        // TODO: test goalTargetMonth
    }

    /**
     * Test the property 'goalPercentageComplete'
     */
    @Test
    public void goalPercentageCompleteTest() {
        // TODO: test goalPercentageComplete
    }

    /**
     * Test the property 'goalMonthsToBudget'
     */
    @Test
    public void goalMonthsToBudgetTest() {
        // TODO: test goalMonthsToBudget
    }

    /**
     * Test the property 'goalUnderFunded'
     */
    @Test
    public void goalUnderFundedTest() {
        // TODO: test goalUnderFunded
    }

    /**
     * Test the property 'goalOverallFunded'
     */
    @Test
    public void goalOverallFundedTest() {
        // TODO: test goalOverallFunded
    }

    /**
     * Test the property 'goalOverallLeft'
     */
    @Test
    public void goalOverallLeftTest() {
        // TODO: test goalOverallLeft
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

}
