/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kickthedrawer.ynab.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kickthedrawer.ynab.model.ScheduledTransactionDetail;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ScheduledTransactionsResponseData
 */
public class ScheduledTransactionsResponseDataTest {
    private final ScheduledTransactionsResponseData model = new ScheduledTransactionsResponseData();

    /**
     * Model tests for ScheduledTransactionsResponseData
     */
    @Test
    public void testScheduledTransactionsResponseData() {
        // TODO: test ScheduledTransactionsResponseData
    }

    /**
     * Test the property 'scheduledTransactions'
     */
    @Test
    public void scheduledTransactionsTest() {
        // TODO: test scheduledTransactions
    }

    /**
     * Test the property 'serverKnowledge'
     */
    @Test
    public void serverKnowledgeTest() {
        // TODO: test serverKnowledge
    }

}
