/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kickthedrawer.ynab.api;

import com.kickthedrawer.ynab.ApiException;
import com.kickthedrawer.ynab.model.BudgetDetailResponse;
import com.kickthedrawer.ynab.model.BudgetSettingsResponse;
import com.kickthedrawer.ynab.model.BudgetSummaryResponse;
import com.kickthedrawer.ynab.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BudgetsApi
 */
@Disabled
public class BudgetsApiTest {

    private final BudgetsApi api = new BudgetsApi();

    /**
     * Single budget
     *
     * Returns a single budget with all related entities.  This resource is effectively a full budget export.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBudgetByIdTest() throws ApiException {
        String budgetId = null;
        Long lastKnowledgeOfServer = null;
        BudgetDetailResponse response = api.getBudgetById(budgetId, lastKnowledgeOfServer);
        // TODO: test validations
    }

    /**
     * Budget Settings
     *
     * Returns settings for a budget
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBudgetSettingsByIdTest() throws ApiException {
        String budgetId = null;
        BudgetSettingsResponse response = api.getBudgetSettingsById(budgetId);
        // TODO: test validations
    }

    /**
     * List budgets
     *
     * Returns budgets list with summary information
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBudgetsTest() throws ApiException {
        Boolean includeAccounts = null;
        BudgetSummaryResponse response = api.getBudgets(includeAccounts);
        // TODO: test validations
    }

}
