/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kickthedrawer.ynab.api;

import com.kickthedrawer.ynab.ApiException;
import com.kickthedrawer.ynab.model.BulkResponse;
import com.kickthedrawer.ynab.model.BulkTransactions;
import com.kickthedrawer.ynab.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeprecatedApi
 */
@Disabled
public class DeprecatedApiTest {

    private final DeprecatedApi api = new DeprecatedApi();

    /**
     * Bulk create transactions
     *
     * Creates multiple transactions.  Although this endpoint is still supported, it is recommended to use &#39;POST /budgets/{budget_id}/transactions&#39; to create multiple transactions.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bulkCreateTransactionsTest() throws ApiException {
        String budgetId = null;
        BulkTransactions transactions = null;
        BulkResponse response = api.bulkCreateTransactions(budgetId, transactions);
        // TODO: test validations
    }

}
