/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kickthedrawer.ynab.api;

import com.kickthedrawer.ynab.ApiException;
import com.kickthedrawer.ynab.model.ErrorResponse;
import java.time.LocalDate;
import com.kickthedrawer.ynab.model.MonthDetailResponse;
import com.kickthedrawer.ynab.model.MonthSummariesResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MonthsApi
 */
@Disabled
public class MonthsApiTest {

    private final MonthsApi api = new MonthsApi();

    /**
     * Single budget month
     *
     * Returns a single budget month
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBudgetMonthTest() throws ApiException {
        String budgetId = null;
        LocalDate month = null;
        MonthDetailResponse response = api.getBudgetMonth(budgetId, month);
        // TODO: test validations
    }

    /**
     * List budget months
     *
     * Returns all budget months
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBudgetMonthsTest() throws ApiException {
        String budgetId = null;
        Long lastKnowledgeOfServer = null;
        MonthSummariesResponse response = api.getBudgetMonths(budgetId, lastKnowledgeOfServer);
        // TODO: test validations
    }

}
