/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kickthedrawer.ynab.api;

import com.kickthedrawer.ynab.ApiException;
import com.kickthedrawer.ynab.model.ErrorResponse;
import com.kickthedrawer.ynab.model.PayeeResponse;
import com.kickthedrawer.ynab.model.PayeesResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PayeesApi
 */
@Disabled
public class PayeesApiTest {

    private final PayeesApi api = new PayeesApi();

    /**
     * Single payee
     *
     * Returns a single payee
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPayeeByIdTest() throws ApiException {
        String budgetId = null;
        String payeeId = null;
        PayeeResponse response = api.getPayeeById(budgetId, payeeId);
        // TODO: test validations
    }

    /**
     * List payees
     *
     * Returns all payees
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPayeesTest() throws ApiException {
        String budgetId = null;
        Long lastKnowledgeOfServer = null;
        PayeesResponse response = api.getPayees(budgetId, lastKnowledgeOfServer);
        // TODO: test validations
    }

}
